### ISSUE TITLE
Add rules for hooks

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/eslint-config#15]
Will help us out as we start using hooks more. 

https://www.npmjs.com/package/eslint-plugin-react-hooks

**Comment by chawes13** [comment]
I came here to create this issue. +1

**Comment by dpikt** [comment]
@chawes13 this has fallen into the "ain't needed it" bucket for me over time. Have you used it/found it helpful on any projects?

**Comment by chawes13** [comment]
I haven't used it yet, but maybe I should pilot it before doubling down on including this. With the team growing and more back-end developers upskilling on the front-end, it may be worth re-evaluating the YAGNI with a different lens

**Comment by dpikt** [comment]
I agree- I think there's most potential for them to be useful in a learning context.
